MIN_CHARS_GATE = 100
MIN_CHARS_AFTER_CLEAN = 300
MIN_CHARS_AFTER_REPAIR = 60
MIN_CHARS_FINAL = 20
HARD_MAX_CHARS = 16000

MAX_CHARS_GATE = 100_000
SCORE_SAMPLE_CHARS = 12_000
MIN_SCORE_LEGACY_METRICS = 0.0

ADAPTIVE_KNOWLEDGE_DENSITY_FLOOR = 18.0
INSTRUCTION_UNWRAP_CHAR_DISCOUNT = 25
INSTRUCTION_UNWRAP_CHAR_MIN = 35
DIVERSITY_DENSITY_DISCOUNT_FLOOR = 18.0
EDUCATIONAL_CODE_DISCOUNT_FLOOR = 10.0
INSTRUCTION_UNWRAP_DENSITY_FLOOR = 8.0

CHUNK_MIN_QUALITY_SCORE_100 = 70.0

DEDUP_FUZZY_THRESHOLD = 0.90
DEDUP_SEMANTIC_JACCARD = 0.72
DEDUP_SEMANTIC_RECENT_JACCARD = 0.75
DEDUP_SEMANTIC_HAMMING = 4
DEDUP_SEMANTIC_MAX_BUCKET = 256

BALANCE_SOFT_CAP_OVERFLOW = 0.15
BALANCE_QUALITY_CAP_BYPASS = 0.86
BALANCE_HIGH_VALUE_DOMAIN_BYPASS = 0.58
BALANCE_MIN_KEPT_BEFORE_CAP = 100

LANGUAGE_MIN_CONFIDENCE = 0.55

DEFAULT_MERGE_WORKERS_CAP = 12
DEFAULT_MERGE_CHUNK_SIZE = 1000
MIN_MERGE_CHUNK_SIZE = 500
MAX_MERGE_CHUNK_SIZE = 5000
DEFAULT_MERGE_BATCH_TIMEOUT_SEC = 120.0
MIN_MERGE_BATCH_TIMEOUT_SEC = 30.0
MERGE_CHECKPOINT_INTERVAL = 250
MERGE_CHECKPOINT_MIN_SAVE_SEC = 60.0
MERGE_CHECKPOINT_FORMAT_VERSION = 1
MERGE_PROGRESS_LOG_INTERVAL = 500
MERGE_METRICS_SNAPSHOT_INTERVAL = 500
METRICS_SNAPSHOT_INTERVAL_SEC = 10.0
MERGE_DOC_WALL_BUDGET_SEC = 90.0
MERGE_DOC_STALL_WARN_SEC = 20.0
MERGE_SCAFFOLD_PROBE_CAP = 48
MERGE_SCAFFOLD_PROBE_WORD_FLOOR = 400
PCI_ENABLED = False
PCI_OBSERVE_ONLY = True

ACIM_ENABLED = True
ACIM_OBSERVE_ONLY = True
ACIM_FAST_PATH = False
ACIM_VERIFY_CONFIDENCE = 0.92
ACIM_MAX_FAMILIES = 50000
ACIM_STORE_VERSION = 'acim-v1'

LCI_ENABLED = True
LCI_OBSERVE_ONLY = True
LCI_GENE_MAX = 200000
LCI_GENE_DECAY_HALF_LIFE_SEC = 90 * 86400
LCI_GENE_VERIFY_CONFIDENCE = 0.55
LCI_INHERITED_VERIFY_CONFIDENCE = 0.50
LCI_STORE_VERSION = 'lci-v2'
LCI_NUM_SHARDS = 1
LCI_GENE_PROMOTE_MIN_OBS = 4
LCI_GENE_PROMOTE_MATCH_STREAK = 3
LCI_FAMILY_PROMOTE_MIN_OBS = 6
LCI_DOMAIN_PROMOTE_MIN_OBS = 12
LCI_INCREMENTAL_OVERLAP_MIN = 0.85
LCI_GENE_RETIRE_UNVERIFIED_DAYS = 180
LCI_PROMOTION_FAMILY_CONF_MIN = 0.72

TEXT_FINGERPRINT_CACHE_SIZE = 8192
SEMANTIC_EVIDENCE_CACHE_SIZE = 4096
RAW_FEATURE_CACHE_SIZE = 4096
NAV_FEATURE_CACHE_SIZE = 2048
PUBLICATION_ROLE_CACHE_SIZE = 2048
STRUCTURE_CACHE_SIZE = 2048
LAYOUT_CACHE_SIZE = 2048
SCAFFOLD_CACHE_SIZE = 2048
CONTENT_FILTERS_CACHE_SIZE = 4096
DEDUP_SQLITE_BATCH_SIZE = 10000
DEDUP_LOOKUP_CACHE_SIZE = 262144
DISCOVERY_FRAGMENT_CACHE_MAX = 250_000

DEFAULT_WRITE_BUFFER_BYTES = 4 * 1024 * 1024
AUDIT_WRITE_BUFFER_BYTES = 8 * 1024 * 1024
HF_STREAM_MIN_ALPHA_RATIO = 0.5

PREPROCESSING_VERSION = 'instant-corpus-v2'
LICENSE_PIPELINE_VERSION = 'instant-license-v1'
TOKEN_SHARD_VERSION = 'instant-token-shard-v1'
CORPUS_REFINE_VERSION = 'instant-corpus-refine-v2'

DEFAULT_QUALITY_SPEC = 'data/filtering/quality_fast_first'
DEFAULT_PIPELINE_SPEC = 'data/pipeline/default'
DEFAULT_REFINER_SPEC = 'data/refining/default'

STRUCT_TRUNC_REPAIR_PROB = 0.35
STRUCT_TRUNC_REMOVE_PROB = 0.72
STRUCT_CODE_DUMP_PROB = 0.55
STRUCT_EDUCATIONAL_CODE_SCORE = 0.25
STRUCT_EDUCATIONAL_SYNTAX_BALANCE = 0.85

DECISION_CODE_HITS_FOR_CODE = 3
DECISION_PROSE_RATIO_FOR_CODE = 0.55
DECISION_CODE_HITS_FOR_MIXED = 2
DECISION_EDUCATIONAL_SCORE_MIXED = 0.1
DECISION_PROSE_RATIO_MIXED = 0.35
DECISION_OCR_MIN_TEXT_CHARS = 80
DECISION_OCR_SINGLE_CHAR_RATIO = 0.12
DECISION_OCR_SINGLE_CHAR_MULT = 4.0
DECISION_OCR_BROKEN_MIN = 2
DECISION_OCR_BROKEN_CHAR_DIV = 300
DECISION_OCR_PIPE_NOISE_RATIO = 0.04
DECISION_OCR_PIPE_NOISE_MULT = 12.0
DECISION_INVALID_SYNTAX_BALANCE = 0.6
DECISION_GENERATED_SCORE_MAX = 0.5
DECISION_SECRET_PII_SCORE = 0.45
DECISION_TRUNCATION_WIKI_EXEMPT = 0.88
DECISION_CODE_SYNTAX_FLOOR = 0.68
DECISION_ALPHA_SYNTAX_FLOOR = 0.5
DECISION_CONFIDENCE_BASE = 0.5
DECISION_SIGNAL_PENALTY_FLOOR = 0.3
DECISION_SIGNAL_PENALTY_WEIGHT = 0.5
DECISION_SOFT_SIGNAL_PENALTY = 0.15
DECISION_ISSUE_COUNT_PENALTY = 3
DECISION_ISSUE_CONFIDENCE_MULT = 0.85
DECISION_SYNTHETIC_EDU_THRESHOLD = 0.5
DECISION_SYNTHETIC_PENALTY_THRESHOLD = 0.4
DECISION_SYNTHETIC_CONFIDENCE_MULT = 0.75
DECISION_LANGUAGE_BLEND_BASE = 0.85
DECISION_LANGUAGE_BLEND_WEIGHT = 0.15
DECISION_CONFIDENCE_MIN = 0.1
DECISION_CONFIDENCE_MAX = 1.0
DECISION_CHARS_PER_TOKEN_FLOOR = 2.5
DECISION_TECHNICAL_DOMAINS = frozenset({'code', 'reasoning', 'docs', 'wiki', 'qa'})
DECISION_TRUNCATION_EXEMPT_DOMAINS = frozenset({'wiki', 'code', 'docs', 'reasoning'})

EMBED_DEDUP_BATCH_SIZE = 16
EMBED_DEDUP_CACHE_SIZE = 8192
EMBED_DEDUP_DIMENSION = 128
EMBED_DEDUP_MAX_CANDIDATES = 32
EMBED_DEDUP_MAX_BUCKET_ENTRIES = 512
EMBED_DEDUP_MAX_GLOBAL_ENTRIES = 50000
